OCAMLMAKEFILE := ../../OCamlMakefile

SOURCES := po_examples.ml hasse.ml
OCAMLFLAGS := -w Aer -strict-sequence
RESULT := hasse

INCDIRS := ../../lib
LIBDIRS := ../../lib

LIBS := pomap

-include $(OCAMLMAKEFILE)
